name: Execute SSH Commands 3

on:
  push:
    branches:
      - main

jobs:
  ssh-remote-command:
    name: Run SSH Commands on Remote Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

          # Test SSH connection
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} "echo 'SSH connection successful'"

          # Remove existing container (ignore errors)
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} "docker rm -f runit || true"
          echo "Container removed or did not exist"

          # Create and start new container
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} "docker run -d -t -p 5001:8000 -p 5002:3000 --name runit gnaskdiashvili/laravelvueinertia"
          echo "Container created and started"

          # Start Apache service inside the container
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} "docker exec runit service apache2 start"

          # Start npm process in detached mode
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} "docker exec runit sh -c 'nohup npm run dev -- --host 0.0.0.0 --port 3000 > /dev/null 2>&1 &'"
          echo "npm process started in detached mode"

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
