name: Execute SSH Commands 3

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger this workflow

jobs:
  ssh-remote-command:
    name: Run SSH Commands on Remote Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 45.79.249.235 >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no root@45.79.249.235 "echo 'SSH connection successful'"
          ssh -o StrictHostKeyChecking=no root@45.79.249.235 "docker rm -f runit"
          ssh -o StrictHostKeyChecking=no root@45.79.249.235 "echo 'remove image'"
          ssh -o StrictHostKeyChecking=no root@45.79.249.235 "docker run -d -t -p 5001:8000 -p 5002:3000 --name runit gnaskdiashvili/laravelvueinertia"
          ssh -o StrictHostKeyChecking=no root@45.79.249.235 "echo 'access image'"
          ssh -o StrictHostKeyChecking=no root@45.79.249.235 "docker exec -it runit bash"
          ssh -o StrictHostKeyChecking=no root@45.79.249.235 "service apache2 start"


        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
